// Seed catalog of 25 verified in-stock sarees across Suta, Karagiri, Soch,
// Raw Mango. Used as a fallback when live agentic search fails (missing API
// key, rate limit, model returns empty, etc.). Products verified 2026-04-25;
// stock decays naturally, so this is best-effort and should be refreshed.
//
// Schema: see lib/catalog/types.ts. Color families and saturation follow
// lib/color/color-theory.md.

import type { CatalogSaree } from './types';

export const CATALOG: CatalogSaree[] = [
  // ---- everyday office / home, summer, ₹1k-3k breathable ----
  {
    id: 'suta-ode-to-greens',
    productName: 'Ode To Greens',
    productUrl: 'https://suta.in/products/ode-to-greens',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/files/IMG_4908.jpg?v=1746612520',
    retailer: 'Suta',
    priceInr: 2500,
    fabric: 'mul cotton',
    fabricFamily: 'cotton',
    dominantColor: 'green_cool',
    saturation: 'muted',
    useCases: ['everyday_office', 'everyday_home'],
    seasonsOk: ['summer', 'monsoon'],
  },
  {
    id: 'suta-yellow-in-jaisalmer',
    productName: 'Yellow In Jaisalmer',
    productUrl: 'https://suta.in/products/yellow-in-jaisalmer',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/products/yellow-in-jaisalmer-699536.jpg?v=1614586638',
    retailer: 'Suta',
    priceInr: 2750,
    fabric: 'mul cotton',
    fabricFamily: 'cotton',
    dominantColor: 'yellow_warm',
    saturation: 'vivid',
    useCases: ['everyday_office', 'everyday_home'],
    seasonsOk: ['summer', 'monsoon'],
  },
  {
    id: 'suta-green-in-mysore',
    productName: 'Green In Mysore',
    productUrl: 'https://suta.in/products/green-in-mysore',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/products/green-in-mysore-678097.jpg?v=1611134625',
    retailer: 'Suta',
    priceInr: 2750,
    fabric: 'soft cotton',
    fabricFamily: 'cotton',
    dominantColor: 'green_warm',
    saturation: 'mid',
    useCases: ['everyday_office', 'everyday_home'],
    seasonsOk: ['summer', 'monsoon'],
  },
  {
    id: 'suta-wine-soaked-olive',
    productName: 'Wine Soaked Olive',
    productUrl: 'https://suta.in/products/made-in-heaven-wine-soaked-olive',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/files/winesoakedoliveDSC_3118.jpg?v=1745489938',
    retailer: 'Suta',
    priceInr: 2500,
    fabric: 'mul cotton',
    fabricFamily: 'cotton',
    dominantColor: 'green_warm',
    saturation: 'muted',
    useCases: ['everyday_office', 'everyday_home'],
    seasonsOk: ['summer', 'monsoon'],
  },
  {
    id: 'suta-off-white-mul-saree',
    productName: 'Off White Mul Saree',
    productUrl: 'https://suta.in/products/off-white-mul-saree',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/products/off-white-mul-saree-199779.jpg?v=1774091199',
    retailer: 'Suta',
    priceInr: 2500,
    fabric: 'mul cotton',
    fabricFamily: 'cotton',
    dominantColor: 'neutral_warm',
    saturation: 'muted',
    useCases: ['everyday_home', 'everyday_office'],
    seasonsOk: ['summer', 'monsoon'],
  },
  {
    id: 'suta-evergreen-in-kerala',
    productName: 'Evergreen In Kerala',
    productUrl: 'https://suta.in/products/evergreen-in-kerala',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/products/evergreen-in-kerala-465318.jpg?v=1616069347',
    retailer: 'Suta',
    priceInr: 2750,
    fabric: 'mul cotton',
    fabricFamily: 'cotton',
    dominantColor: 'green_cool',
    saturation: 'mid',
    useCases: ['everyday_home', 'everyday_office'],
    seasonsOk: ['summer', 'monsoon'],
  },
  {
    id: 'suta-khilta-dil',
    productName: 'Khilta Dil',
    productUrl: 'https://suta.in/products/khilta-dil',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/products/khilta-dil-947839.jpg?v=1666854510',
    retailer: 'Suta',
    priceInr: 3250,
    fabric: 'handloom cotton',
    fabricFamily: 'cotton',
    dominantColor: 'pink_warm',
    saturation: 'muted',
    useCases: ['everyday_office', 'everyday_home'],
    seasonsOk: ['summer', 'monsoon'],
  },
  {
    id: 'suta-inked-star',
    productName: 'Inked Star',
    productUrl: 'https://suta.in/products/inked-star',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/products/inked-star-471703.jpg?v=1614596743',
    retailer: 'Suta',
    priceInr: 3450,
    fabric: 'mul cotton',
    fabricFamily: 'cotton',
    dominantColor: 'purple',
    saturation: 'mid',
    useCases: ['everyday_office'],
    seasonsOk: ['summer', 'monsoon'],
  },
  {
    id: 'karagiri-mustard-yellow-cotton-64901',
    productName: 'Mustard Yellow Cotton Saree',
    productUrl: 'https://www.karagiri.com/products/mustard-yellow-cotton-saree-64901',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1760/4649/products/cotton-saree-mustard-yellow-cotton-saree-silk-saree-online-30932937146561.jpg?v=1648565743',
    retailer: 'Karagiri',
    priceInr: 3249,
    fabric: 'cotton',
    fabricFamily: 'cotton',
    dominantColor: 'yellow_warm',
    saturation: 'mid',
    useCases: ['everyday_office'],
    seasonsOk: ['summer', 'monsoon', 'winter'],
  },
  {
    id: 'suta-floral-pure-cotton',
    productName: 'Suta Floral Pure Cotton Saree',
    productUrl: 'https://suta.in/products/suta-floral-pure-cotton-saree',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/files/SUTATP0657-1.jpg?v=1744269010',
    retailer: 'Suta',
    priceInr: 3100,
    fabric: 'pure cotton',
    fabricFamily: 'cotton',
    dominantColor: 'neutral_cool',
    saturation: 'muted',
    useCases: ['everyday_office', 'everyday_home'],
    seasonsOk: ['summer', 'monsoon'],
  },

  // ---- cotton-silk blend bridge (office + occasion day events) ----
  {
    id: 'suta-satviki',
    productName: 'Satviki',
    productUrl: 'https://suta.in/products/satviki',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/products/satviki-463639.jpg?v=1611323638',
    retailer: 'Suta',
    priceInr: 5550,
    fabric: 'maheshwari',
    fabricFamily: 'cotton_silk',
    dominantColor: 'orange_earth',
    saturation: 'muted',
    useCases: ['everyday_office', 'special_occasion'],
    seasonsOk: ['summer', 'monsoon', 'winter'],
  },

  // ---- special occasion day events ----
  {
    id: 'karagiri-mustard-yellow-raw-silk-99413',
    productName: 'Mustard Yellow Raw Silk Saree With Blouse Piece',
    productUrl: 'https://www.karagiri.com/products/mustard-yellow-raw-silk-saree-with-blouse-piece-99413',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1760/4649/files/HDLM-385-YELLOW-1.jpg?v=1701165431',
    retailer: 'Karagiri',
    priceInr: 2749,
    fabric: 'raw silk',
    fabricFamily: 'silk',
    dominantColor: 'yellow_warm',
    saturation: 'mid',
    useCases: ['special_occasion'],
    seasonsOk: ['summer', 'winter', 'monsoon'],
  },
  {
    id: 'karagiri-pink-green-paithani-86684',
    productName: 'Pink And Green Paithani Silk Saree',
    productUrl: 'https://www.karagiri.com/products/pink-and-green-paithani-silk-saree-86684',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1760/4649/products/rzpis-2739_3_52546709988_o.jpg?v=1672815957',
    retailer: 'Karagiri',
    priceInr: 2899,
    fabric: 'paithani silk',
    fabricFamily: 'silk',
    dominantColor: 'pink_warm',
    saturation: 'vivid',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },
  {
    id: 'karagiri-green-pink-paithani-70230',
    productName: 'Green And Pink Paithani Silk Saree',
    productUrl: 'https://www.karagiri.com/products/green-and-pink-paithani-silk-saree-70230',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1760/4649/products/rzpis-2742_3_52545700342_o.jpg',
    retailer: 'Karagiri',
    priceInr: 2899,
    fabric: 'paithani silk',
    fabricFamily: 'silk',
    dominantColor: 'green_warm',
    saturation: 'vivid',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },
  {
    id: 'karagiri-pastel-green-kanjivaram-26261',
    productName: 'Pastel Green Kanjivaram Silk Saree',
    productUrl: 'https://www.karagiri.com/products/pastel-green-kanjivaram-silk-saree-26261',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1760/4649/products/pavitra-rishta-3651_3_52552340816_o.jpg?v=1672638242',
    retailer: 'Karagiri',
    priceInr: 4349,
    fabric: 'kanjivaram silk',
    fabricFamily: 'silk',
    dominantColor: 'green_cool',
    saturation: 'muted',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },

  // ---- special occasion, evening/festive, ₹2k-6k ----
  {
    id: 'karagiri-magenta-banarasi-78801',
    productName: 'Magenta Banarasi Saree With Blouse Piece',
    productUrl: 'https://www.karagiri.com/products/magenta-banarasi-saree-78801',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1760/4649/products/banarasi-saree-magenta-banarasi-saree-silk-saree-online-31822517862593.jpg?v=1766039313',
    retailer: 'Karagiri',
    priceInr: 2199,
    fabric: 'banarasi',
    fabricFamily: 'synthetic',
    dominantColor: 'pink_warm',
    saturation: 'vivid',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },
  {
    id: 'karagiri-mahogany-maroon-banarasi-40839',
    productName: 'Mahogany Maroon Banarasi Saree',
    productUrl: 'https://www.karagiri.com/products/mahogany-maroon-banarasi-saree-40839',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1760/4649/products/banarasi-saree-mahogany-maroon-banarasi-saree-silk-saree-online-31828994097345.jpg?v=1765538142',
    retailer: 'Karagiri',
    priceInr: 2649,
    fabric: 'banarasi',
    fabricFamily: 'synthetic',
    dominantColor: 'red_warm',
    saturation: 'vivid',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },
  {
    id: 'karagiri-royal-blue-banarasi-57044',
    productName: 'Royal Blue Banarasi Silk Saree With Blouse',
    productUrl: 'https://www.karagiri.com/products/royal-blue-banarasi-silk-saree-with-blouse-57044',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1760/4649/files/zamdani-silk-5011_3.jpg?v=1695629461',
    retailer: 'Karagiri',
    priceInr: 5299,
    fabric: 'banarasi silk',
    fabricFamily: 'silk',
    dominantColor: 'blue_cool',
    saturation: 'vivid',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },
  {
    id: 'karagiri-teal-green-kanjivaram',
    productName: 'Teal Green Kanjivaram Saree',
    productUrl: 'https://www.karagiri.com/products/teal-green-handcrafted-customised-kanjivaram-saree',
    imageUrl: 'https://cdn.shopify.com/s/files/1/1760/4649/products/kanjivaram-saree-teal-green-handcrafted-kanjivaram-saree-silk-saree-online-24543263948993.jpg?v=1648626401',
    retailer: 'Karagiri',
    priceInr: 5449,
    fabric: 'kanjivaram silk',
    fabricFamily: 'silk',
    dominantColor: 'green_cool',
    saturation: 'vivid',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },
  {
    id: 'soch-navy-blue-chiffon-119973a',
    productName: 'Navy Blue Chiffon Floral Print Saree With Stone Work',
    productUrl: 'https://www.soch.com/in/navy-blue-chiffon-floral-print-saree-with-stone-work-srevebl119973a.html',
    imageUrl: 'https://www.soch.com/media/catalog/product/n/a/navy_blue_chiffon_floral_print_saree_with_stone_work_womens_soch-srevebl119973a_01.jpg',
    retailer: 'Soch',
    priceInr: 4199,
    fabric: 'chiffon',
    fabricFamily: 'synthetic',
    dominantColor: 'blue_cool',
    saturation: 'vivid',
    useCases: ['special_occasion', 'everyday_office'],
    seasonsOk: ['summer', 'monsoon'],
  },
  {
    id: 'soch-powder-blue-georgette-125492e',
    productName: 'Powder Blue Georgette Embroidered Saree',
    productUrl: 'https://www.soch.com/in/powder-blue-georgette-embroidered-saree-srevemb125492e.html',
    imageUrl: 'https://www.soch.com/media/catalog/product/p/o/powder_blue_georgette_embroidered_saree_womens_soch-srevemb125492e_01.jpg',
    retailer: 'Soch',
    priceInr: 5998,
    fabric: 'georgette',
    fabricFamily: 'synthetic',
    dominantColor: 'blue_cool',
    saturation: 'muted',
    useCases: ['special_occasion', 'everyday_office'],
    seasonsOk: ['summer', 'monsoon', 'winter'],
  },

  // ---- special occasion premium / mid silks ₹13k-45k ----
  {
    id: 'suta-sable',
    productName: 'Sable',
    productUrl: 'https://suta.in/products/sable',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/products/sable-944400.jpg?v=1745480432',
    retailer: 'Suta',
    priceInr: 13750,
    fabric: 'chanderi silk',
    fabricFamily: 'silk',
    dominantColor: 'blue_cool',
    saturation: 'vivid',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },
  {
    id: 'suta-cashmere',
    productName: 'Cashmere',
    productUrl: 'https://suta.in/products/cashmere',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/products/cashmere-829105.jpg?v=1693902481',
    retailer: 'Suta',
    priceInr: 13750,
    fabric: 'chanderi silk',
    fabricFamily: 'silk',
    dominantColor: 'purple',
    saturation: 'vivid',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },
  {
    id: 'suta-aadira',
    productName: 'Aadira',
    productUrl: 'https://suta.in/products/aadira',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0026/6544/7536/files/DSC_7357_a22f1c5a-59c6-49a0-b30e-4145865ecdbd.jpg?v=1732542305',
    retailer: 'Suta',
    priceInr: 26500,
    fabric: 'kanjivaram silk',
    fabricFamily: 'silk',
    dominantColor: 'neutral_warm',
    saturation: 'muted',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },
  {
    id: 'rawmango-jhirni-rani',
    productName: 'Jhirni',
    productUrl: 'https://rawmango.com/products/jhirni-rani',
    imageUrl: 'https://cdn.shopify.com/s/files/1/0262/6315/8833/files/20251229-RM_0489.jpg?v=1771566128',
    retailer: 'Raw Mango',
    priceInr: 35800,
    fabric: 'banarasi brocade',
    fabricFamily: 'silk',
    dominantColor: 'pink_warm',
    saturation: 'vivid',
    useCases: ['special_occasion'],
    seasonsOk: ['winter', 'monsoon'],
  },
];
